// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vevkimrlwmmxojkayxui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldmtpbXJsd21teG9qa2F5eHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODg2OTYsImV4cCI6MjA3MzY2NDY5Nn0.uUNijD6JEcFu9DMaS9qDQOI7ENiwoFbmWf-xEP4mSkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});